seed: 42
project: "g3m"
tags:
  - qm9
train: true

# logging-specific
log_dir: ${oc.env:LOG_PATH}
output_dir: ${hydra:runtime.output_dir}
work_dir: ${hydra:runtime.cwd}

# data-specific
data_path: ${oc.env:DATA_PATH}/qm9/preprocessed
infos_path: ${data_path}/train_infos.json
data_name: "qm9"
atom_types_str: [ "H", "C", "N", "O", "F" ]
max_num_atoms: 29
remove_h: false

# model-specific
zero_cog: true
num_layers: 8
hidden_dim: 256
num_fourier_features: 16
num_rbf_features: 64
max_distance: 12.0 # QM9-specific
parameterization: "x0"

# TRM / self-cond specific
self_conditioning: true        #self-conditioning: whether to use self-conditioning 
latent_recursion: true  #latent-recursion: whether to use latent recursion (ASSUMES self-conditioning == True)
update_edge_states: false #update edge states
n: 1 #latent-recursion: REQUIREMENT n>=0, number of latent recursion steps
K: 2 #deep-recursion: REQUIREMENT K>=2,number of deep recursion steps 
M: 8 #latent-recursion: scratchpad number of tokens
z_dim: 64 #64 #latent-recursion: scratchpad latent dim
scprop: 0.5 #self-conditioning and latent recursion: 1 means no skipping 0 means all skipping. We SKIP if rand(1) > scprop

# Classifier-Free Guidance (CFG) shape conditioning
train_cfg: false
guidance_method: "cfg" # "cfg", "cg_standard_gradient_wrt_xt", "cg_self_conditioned_gradient_wrt_x0"
guidance_lambda: 0.01
guidance_thinking_steps: 1
cfg_prop: 0.5
cfg_property: "eigenvalues_and_scale"
cfg_scale: 1.0
use_scale: false
condition_dim: 3

# distogram specific
# Set pair_dist_loss to "none" to completely disable distogram prediction
pair_dist_loss: "none" # options: "none", "mse", "huber_masked", "distogram" 
pair_dist_loss_coefficient: 0.1
distogram_bins: 65 #only used for "distogram"
distogram_cutoff: 5.12 #roughly the interraction horizon, similar philosophy to alphafold
distogram_mask_cutoff: 2.0 #relevant only for "huber_masked"
pair_dist_huber_delta: 1.0 #transition point from L2 to L1 in huber loss
permutation_invariant_loss: "none" # options: "none",, "sinkhorn"

ablations:
  ablate_s: false
  ablate_v: false
  ablate_edge: false
  ablate_unit_vectors: false

# validation
monitor_metric: "val/molecule_stable"
val_every_n_epochs: 5


datamodule:
  _target_: src_gmmm.data.datamodule.DataModule
  remove_h: ${remove_h}
  transform:
    _target_: torch_geometric.transforms.Compose
    transforms:
      - _target_: src_gmmm.data.transforms.FullyConnected
      - _target_: src_gmmm.data.transforms.ZeroCoG
        key: "pos"

  train_path: ${data_path}/train.pt
  val_path: ${data_path}/val.pt
  train_batch_size: 64
  val_batch_size: 256
  num_val_subset: 2048
  redraw_val_subset: true
  num_workers: 1
  pin_memory: true
  subset_seed: ${seed}

lit_module:
  _target_: src_gmmm.lit.module.LitModule
  cfg_scale: ${cfg_scale}
  pair_dist_loss_coefficient: ${pair_dist_loss_coefficient}

  model:
    _target_: src_gmmm.model.diffusion.EquivariantDiffusion

    diffusion_h: null   #Currently we ONLY compute loss from eucledian positions
    scprop: ${scprop}         #self-conditioning: probability of using self-conditioning (ONLY used when self_conditioning is true)
    self_conditioning: ${self_conditioning}
    latent_recursion: ${latent_recursion}
    n: ${n}
    K: ${K}
    
    train_cfg: ${train_cfg}
    guidance_method: ${guidance_method}
    guidance_lambda: ${guidance_lambda}
    guidance_thinking_steps: ${guidance_thinking_steps}
    cfg_prop: ${cfg_prop}
    cfg_property: ${cfg_property}
    use_scale: ${use_scale}
    pair_dist_loss: ${pair_dist_loss}
    distogram_bins: ${distogram_bins}
    distogram_cutoff: ${distogram_cutoff}
    distogram_mask_cutoff: ${distogram_mask_cutoff}
    pair_dist_huber_delta: ${pair_dist_huber_delta}
    permutation_invariant_loss: ${permutation_invariant_loss}
    
    parameterization:
      _target_: src_gmmm.model.score.EquivariantParameterization
      encoder:
        _target_: src_gmmm.nn.encoder.EquivEncoder
        hidden_dim: ${hidden_dim}
        time_embedding:
          _target_: src_gmmm.nn.layers.FourierEmbedding
          in_features: 1
          out_features: ${num_fourier_features}
        edge_embedding:
          _target_: src_gmmm.nn.layers.EdgeEmbedding
          num_rbf_features: ${num_rbf_features}
          max_distance: ${max_distance}
        num_layers: ${num_layers}
        smooth_h: false
        self_conditioning: ${self_conditioning}        #self-conditioning: whether to use self-conditioning 
        h_input_dim: 100 # all periodic table
        latent_recursion: ${latent_recursion} #latent-recursion: whether to use latent recursion
        update_edge_states: ${update_edge_states}
        M: ${M} #latent-recursion: height of scratchpad
        z_dim: ${z_dim} #latent-recursion: dimensionality of scratchpad
        ablations: ${ablations}
        condition_dim: ${condition_dim}

      readout:
        _target_: src_gmmm.nn.readout.DataPointReadout
        hidden_dim: ${hidden_dim}
        num_rbf_features: ${num_rbf_features}
        pred_h: false
        pred_pos: true
        zero_cog: ${zero_cog}
        parameterization: "residual-time"

    diffusion_pos:
      _target_: src_gmmm.model.continuous.ContinuousDiffusion
      sde:
        _target_: src_gmmm.model.continuous.LinearLogSNRVPSDE
      parameterization: ${parameterization}
      distribution:
        _target_: src_gmmm.model.distributions.DistributionGaussian
        dim: 3
        zero_cog: ${zero_cog}


  metrics:
    # _target_: src_gmmm.metrics.qm9.QM9Metrics
    _target_: src_gmmm.metrics.geom_drugs.GeomDrugsMetrics
    atom_types_str: ${atom_types_str}
    max_num_atoms: ${max_num_atoms}
    json_path: ${infos_path}
    remove_h: ${remove_h}



  n_integration_steps: 250
  lr: 2e-4
  warm_up_steps: 100
  with_ema: true
  ema_start_step: 500
  ema_decay: 0.999
  antithetic_time_sampling: true
  loss_during_val: true


callbacks:
  model_checkpoint:
    _target_: pytorch_lightning.callbacks.ModelCheckpoint

    dirpath: ${output_dir}/checkpoints
    filename: "{epoch:03d}"
    monitor: ${monitor_metric}
    verbose: False
    save_last: true
    save_top_k: 3
    mode: "max"
    auto_insert_metric_name: true
    save_weights_only: false
    every_n_epochs: ${val_every_n_epochs}
    save_on_train_epoch_end: false

  representation_tracker:
    _target_: src_gmmm.utils.tracking.RepresentationTrackerCallback
    frequency: "val_first_and_last" 
    modules:
      - "probes.post_sc_s"
      - "probes.layer_0_s"
      
  log_sampled_atoms:
    _target_: src_gmmm.utils.callback.LogSampledAtomsCallback
    dirpath: ${output_dir}/samples
    save_atoms: true
    num_log_wandb: 25
    atom_type_pairwise_distogram_plots: true

logger:
  wandb:
    _target_: pytorch_lightning.loggers.wandb.WandbLogger
    save_dir: ${output_dir}
    name: null  
    offline: False
    id: null
    anonymous: null
    project: ${project}
    log_model: False
    prefix: ""
    group: ""
    tags: ${tags}
    job_type: ""

  csv:
    _target_: pytorch_lightning.loggers.CSVLogger
    save_dir: ${output_dir}
    name: "csv_logs"


trainer:
  _target_: pytorch_lightning.Trainer
  accelerator: auto
  devices: 1
  gradient_clip_val: 1.0
  gradient_clip_algorithm: "norm"
  max_epochs: 1000
  check_val_every_n_epoch: ${val_every_n_epochs}
  num_sanity_val_steps: 1


hydra:
  run:
    dir: ${log_dir}/${data_name}/runs/${now:%Y-%m-%d}_${now:%H-%M-%S}
